/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const NoteId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Note = IDL.Record({
  'id' : NoteId,
  'title' : IDL.Text,
  'externalBlob' : ExternalBlob,
  'owner' : IDL.Principal,
  'mimeType' : IDL.Text,
  'filename' : IDL.Text,
  'summary' : IDL.Opt(IDL.Text),
  'uploadDate' : IDL.Int,
  'textContent' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const NoteMetadata = IDL.Record({
  'id' : NoteId,
  'hasSummary' : IDL.Bool,
  'title' : IDL.Text,
  'mimeType' : IDL.Text,
  'filename' : IDL.Text,
  'uploadDate' : IDL.Int,
});
export const SaveNoteRequest = IDL.Record({
  'title' : IDL.Text,
  'externalBlob' : ExternalBlob,
  'mimeType' : IDL.Text,
  'filename' : IDL.Text,
  'textContent' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'askQuestion' : IDL.Func([NoteId, IDL.Text], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteNote' : IDL.Func([NoteId], [], []),
  'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getNote' : IDL.Func([NoteId], [IDL.Opt(Note)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRole' : IDL.Func([IDL.Principal], [UserRole], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listNotes' : IDL.Func([], [IDL.Vec(NoteMetadata)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveNote' : IDL.Func([SaveNoteRequest], [NoteId], []),
  'summarizeNote' : IDL.Func([NoteId], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const NoteId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Note = IDL.Record({
    'id' : NoteId,
    'title' : IDL.Text,
    'externalBlob' : ExternalBlob,
    'owner' : IDL.Principal,
    'mimeType' : IDL.Text,
    'filename' : IDL.Text,
    'summary' : IDL.Opt(IDL.Text),
    'uploadDate' : IDL.Int,
    'textContent' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const NoteMetadata = IDL.Record({
    'id' : NoteId,
    'hasSummary' : IDL.Bool,
    'title' : IDL.Text,
    'mimeType' : IDL.Text,
    'filename' : IDL.Text,
    'uploadDate' : IDL.Int,
  });
  const SaveNoteRequest = IDL.Record({
    'title' : IDL.Text,
    'externalBlob' : ExternalBlob,
    'mimeType' : IDL.Text,
    'filename' : IDL.Text,
    'textContent' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'askQuestion' : IDL.Func([NoteId, IDL.Text], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteNote' : IDL.Func([NoteId], [], []),
    'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getNote' : IDL.Func([NoteId], [IDL.Opt(Note)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRole' : IDL.Func([IDL.Principal], [UserRole], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listNotes' : IDL.Func([], [IDL.Vec(NoteMetadata)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveNote' : IDL.Func([SaveNoteRequest], [NoteId], []),
    'summarizeNote' : IDL.Func([NoteId], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };